spring:
  shell:
    command:
      history:
        enabled: false
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/main_data
    username: admin
    password: adminpwd
    # environment variable
    #    password: ${metalake_password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update

web:
  enable_debug: false